# Pytorch

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter('ignore')

!pip install torch
import torch


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip


<a id="1.0"></a>
## 1.0. Синтаксис

Some facts about PyTorch:  
- dynamic computation graph
- handy `torch.nn` and `torchvision` modules for fast neural network prototyping
- even faster than TensorFlow on some tasks
- allows to use GPU easily

If PyTorch was a formula, it would be:  

$$PyTorch = NumPy + CUDA + Autograd$$

CUDA - [wiki](https://en.wikipedia.org/wiki/CUDA), Autograd - https://pytorch.org/docs/stable/autograd.html

Let's see how we can use PyTorch to operate with vectors and tensors.  

Recall that **a tensor** is a multidimensional vector, e.g. :  

`x = np.array([1,2,3])` -- a vector = a tensor with 1 dimension (to be more precise: `(1,)`)  
`y = np.array([[1, 2, 3], [4, 5, 6]])` -- a matrix = a tensor with 2 dimensions (`(2, 3)` in this case)  
`z = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])` -- "a cube" (3, 3, 3) = a tensor with 3 dimensions (`(3, 3, 3)` in this case)

One real example of 3-dimensional tensor is **an image**, it has 3 dimensions: `height`, `width` and the `channel depth` (= 3 for color images, 1 for a greyscale). You can think of it as of parallelepiped consisting of the real numbers.

In PyTorch we will use `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`) for all the computations.

All tensor types:

In [3]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

We will use only `torch.FloatTensor()` and `torch.IntTensor()`.

Let's begin to do something!

* Creating the tensor:

In [4]:
a = torch.FloatTensor([1, 2])
a

tensor([1., 2.])

In [5]:
a.shape

torch.Size([2])

In [6]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
b.shape

torch.Size([2, 3])

In [8]:
x = torch.FloatTensor(2,3,4)

In [9]:
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
x = torch.FloatTensor(100)
x

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [11]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Note:** if you create `torch.Tensor` with the following constructor it will be filled with the "random trash numbers":

In [12]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32)

Here is a way to fill a new tensor with zeroes:

In [13]:
x = torch.FloatTensor(3, 2, 4).zero_()
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

<a id="1.1"></a>
## 1.1. Операции в PyTorch

All numpy function have its pair in torch.

https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

`np.reshape()` == `torch.view()`:

In [14]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [15]:
b.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

**Note:** `torch.view()` creates a new tensor, one the old one remains unchanged

In [16]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [17]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

* Change a tensor type:

In [18]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [19]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [20]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

**Note:** `.type_as()` creates a new tensor, the old one remains unchanged

In [21]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Indexing is just like in `NumPy`:

In [22]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [23]:
a[0, 0]

tensor(100.)

In [ ]:
# Срезы
a[0:2, 0:2]

tensor([[100.,  20.],
        [ 15., 163.]])

**Ariphmetics and boolean operations** and their analogues:  

| Operator | Analogue |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

* Addition:

In [25]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [26]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [27]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [28]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [29]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

* Subtraction:

In [30]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [31]:
a.sub(b)

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

* Multiplication (elementwise):

In [32]:
a * b

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

In [33]:
a.mul(b)

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

* Division (elementwise):

In [34]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [35]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

In [36]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

**Note:** all this operations create new tensors, the old tensors remain unchanged

In [37]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [38]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

* Comparison operators:

In [39]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [40]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [41]:
a != b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

In [42]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [43]:
a > b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

* Using boolean mask indexing:

In [44]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [45]:
b[a == b]

tensor([100., 200., 300.])

Elementwise application of the **universal functions**:

In [46]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [47]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [48]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [49]:
a.tan()

tensor([[ 1.5574, -2.1850, -0.1425],
        [ 0.6484,  2.2372, -6.4053],
        [-0.5872, -1.7925, 45.2447]])

In [50]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [51]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [52]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [53]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* The sum, mean, max, min:

In [54]:
a.sum()

tensor(666.)

In [55]:
a.mean()

tensor(74.)

Along axis:

In [56]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [57]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [58]:
a.sum(1)

tensor([  6.,  60., 600.])

In [59]:
a.max()

tensor(300.)

In [60]:
a.max(0)

torch.return_types.max(
values=tensor([100., 200., 300.]),
indices=tensor([2, 2, 2]))

In [61]:
a.min()

tensor(1.)

In [62]:
a.min(0)

torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))

**Note:** the second tensor returned by `.max()` and `.min()` contains the indices of max/min elements along this axis. E.g. in that case `a.min()` returned `(1, 2, 3)` which are the minimum elements along 0 axis (along columns) and their indices along 0 axis are `(0, 0, 0)`.

<a id="1.3"></a>
## 1.3. Matrix operations

* Transpose a tensor:

In [63]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [64]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

It is not not the inplace operation too:

In [65]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* Dot product of vectors:

In [66]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [67]:
a.dot(b)

tensor(-141.)

In [68]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [69]:
a @ b

tensor(-141.)

In [70]:
type(a)

torch.Tensor

In [71]:
type(b)

torch.Tensor

In [72]:
type(a @ b)

torch.Tensor

* Matrix product:

In [73]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [74]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [75]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

Remain unchanged:

In [76]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [77]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

In [78]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [79]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [80]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

If we unroll the tensor `b` in an array (`torch.view(-1)`) the multiplication would be like with the column:

In [81]:
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [82]:
b.view(-1)

tensor([ -1., -10., 100.])

In [83]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [84]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

<a id="1.4"></a>
## 1.4. From NumPy to PyTorch conversion

In [85]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.74533091, 0.71353149, 0.39012568],
       [0.38143772, 0.06708228, 0.83261896],
       [0.20498112, 0.8544887 , 0.42279325]])

In [86]:
b = torch.from_numpy(a)
b

tensor([[0.7453, 0.7135, 0.3901],
        [0.3814, 0.0671, 0.8326],
        [0.2050, 0.8545, 0.4228]], dtype=torch.float64)

**NOTE!** `a` and `b` have the same data storage, so the changes in one tensor will lead to the changes in another:

In [87]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [88]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

From PyTorch to NumPy conversion:

In [89]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [90]:
type(a)

torch.Tensor

In [91]:
x = a.numpy()
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [92]:
x.shape

(2, 3, 4)

In [93]:
type(x)

numpy.ndarray

In [94]:
x -= x

In [95]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Let's write the `forward_pass(X, w)` ($w_0$ is a part of the $w$) for a single neuron (activation = sigmoid) using PyTorch:

In [96]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

In [97]:
X = torch.FloatTensor([[-5, 5],
                       [2, 3],
                       [1, -1]])

w = torch.FloatTensor([[-0.5],
                       [2.5]])

result = forward_pass(X, w)
print('result: {}'.format(result))

result: tensor([[1.0000],
        [0.9985],
        [0.0474]])


<a id="1.5"></a>
## 1.5. CUDA / MPS

[CUDA documentation](https://docs.nvidia.com/cuda/)

We can use both CPU (Central Processing Unit) and GPU (Graphical Processing Unit) to make the computations with PyTorch. We can switch between them easily, this is one of the most important things in PyTorch framework.

How to make CUDA available on your computer: https://pytorch.org/get-started/locally/

In [ ]:
torch.cuda.is_available()
## Apple M-processors
torch.mps.is_available()

True

In [99]:
x = torch.FloatTensor(1024, 1024).uniform_()
x

tensor([[0.8018, 0.9720, 0.3344,  ..., 0.3593, 0.9169, 0.0836],
        [0.5666, 0.1085, 0.2912,  ..., 0.9195, 0.2515, 0.2538],
        [0.5289, 0.3995, 0.3530,  ..., 0.7604, 0.3420, 0.7950],
        ...,
        [0.3667, 0.4341, 0.0217,  ..., 0.1362, 0.4737, 0.1871],
        [0.0330, 0.4226, 0.6212,  ..., 0.4673, 0.7295, 0.2269],
        [0.0189, 0.7440, 0.9439,  ..., 0.9964, 0.8508, 0.6616]])

In [100]:
x.is_cuda

False

Place a tensor on GPU:

In [105]:
x = x.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
x

tensor([[0.7112, 0.7757, 0.2223,  ..., 0.4191, 0.5914, 0.7430],
        [0.5141, 0.2467, 0.5363,  ..., 0.5746, 0.5101, 0.2517],
        [0.1281, 0.1432, 0.4105,  ..., 0.1036, 0.1857, 0.3060],
        ...,
        [0.9499, 0.3148, 0.8677,  ..., 0.2581, 0.4522, 0.2834],
        [0.1261, 0.4013, 0.6516,  ..., 0.3368, 0.3668, 0.6092],
        [0.8631, 0.7663, 0.2670,  ..., 0.2889, 0.4286, 0.0615]],
       device='cuda:0')

In [ ]:
# device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
device = torch.device("cuda:0")
x = x.to(device)
x

tensor([[0.7112, 0.7757, 0.2223,  ..., 0.4191, 0.5914, 0.7430],
        [0.5141, 0.2467, 0.5363,  ..., 0.5746, 0.5101, 0.2517],
        [0.1281, 0.1432, 0.4105,  ..., 0.1036, 0.1857, 0.3060],
        ...,
        [0.9499, 0.3148, 0.8677,  ..., 0.2581, 0.4522, 0.2834],
        [0.1261, 0.4013, 0.6516,  ..., 0.3368, 0.3668, 0.6092],
        [0.8631, 0.7663, 0.2670,  ..., 0.2889, 0.4286, 0.0615]],
       device='cuda:0')

Let's multiply two tensors on GPU and then move the result on the CPU:

In [ ]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
c

tensor([[0.2906, 0.1012, 0.1454,  ..., 0.8877, 0.0288, 0.3025],
        [0.1290, 0.0955, 0.1436,  ..., 0.2631, 0.6261, 0.3389],
        [0.0706, 0.2446, 0.0259,  ..., 0.2638, 0.1647, 0.0900],
        ...,
        [0.0487, 0.7812, 0.6269,  ..., 0.0665, 0.3746, 0.5748],
        [0.0239, 0.4832, 0.0510,  ..., 0.8085, 0.0618, 0.7476],
        [0.1681, 0.1189, 0.2402,  ..., 0.1543, 0.0224, 0.0641]])

In [ ]:
a

tensor([[0.8707, 0.3839, 0.2151,  ..., 0.9423, 0.7693, 0.4870],
        [0.1341, 0.4889, 0.2106,  ..., 0.8436, 0.7176, 0.3882],
        [0.2385, 0.4313, 0.0895,  ..., 0.6795, 0.5297, 0.0980],
        ...,
        [0.2228, 0.8435, 0.9973,  ..., 0.0702, 0.4665, 0.7604],
        [0.1075, 0.6198, 0.0651,  ..., 0.8941, 0.5287, 0.7687],
        [0.1910, 0.1653, 0.2763,  ..., 0.6602, 0.4450, 0.2614]])

Tensors placed on CPU and tensors placed on GPU are unavailable for each other:

In [ ]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [ ]:
a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Example of working with GPU:

In [ ]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# check for CUDA availability (NVIDIA GPU)
if torch.cuda.is_available():
    # get the CUDA device name
    device = torch.device('cuda')          # CUDA-device object
    y = torch.ones_like(x, device=device)  # create a tensor on GPU
    x = x.to(device)                       # or just `.to("cuda")`
    z = x + y
    print(z)
    # you can set the type while `.to` operation
    print(z.to("cpu", torch.double))

tensor([[[1.1872, 1.9296, 1.6814, 1.8405, 1.0863],
         [1.7544, 1.1572, 1.8935, 1.7637, 1.7742],
         [1.9164, 1.2485, 1.3101, 1.5230, 1.5133],
         [1.7918, 1.2989, 1.1930, 1.5344, 1.0650],
         [1.4317, 1.0397, 1.0704, 1.2111, 1.8472]],

        [[1.1582, 1.2748, 1.4116, 1.8418, 1.7405],
         [1.8494, 1.1515, 1.9600, 1.7828, 1.0083],
         [1.1242, 1.3142, 1.6898, 1.8658, 1.3516],
         [1.4896, 1.9422, 1.0856, 1.6185, 1.4264],
         [1.9579, 1.4115, 1.5320, 1.3412, 1.8282]],

        [[1.0954, 1.9450, 1.2926, 1.7483, 1.7889],
         [1.1068, 1.3932, 1.3706, 1.4671, 1.0285],
         [1.0474, 1.3161, 1.8991, 1.3529, 1.7590],
         [1.7975, 1.5188, 1.4693, 1.1437, 1.8687],
         [1.4624, 1.1627, 1.4390, 1.4618, 1.9565]],

        [[1.8681, 1.1932, 1.6342, 1.0456, 1.1095],
         [1.5014, 1.3888, 1.7643, 1.0012, 1.1704],
         [1.1838, 1.9928, 1.9443, 1.8139, 1.4615],
         [1.8308, 1.1566, 1.7231, 1.5972, 1.6277],
         [1.0589, 1.2965,

<a id="3"></a>
# 3. Ссылки

*1). Official PyTorch tutorials: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py*

*2). arXiv article about the deep learning frameworks comparison: https://arxiv.org/pdf/1511.06435.pdf*

*3). Useful repo with different tutorials: https://github.com/yunjey/pytorch-tutorial*

*4). Facebook AI Research (main contributor of PyTorch) website: https://facebook.ai/developers/tools*

### More about pytorch:
* Using torch on GPU and multi-GPU - [link](http://pytorch.org/docs/master/notes/cuda.html)
* More tutorials on pytorch - [link](http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)
* Pytorch examples - a repo that implements many cool DL models in pytorch - [link](https://github.com/pytorch/examples)
* Practical pytorch - a repo that implements some... other cool DL models... yes, in pytorch - [link](https://github.com/spro/practical-pytorch)
* And some more - [link](https://www.reddit.com/r/pytorch/comments/6z0yeo/pytorch_and_pytorch_tricks_for_kaggle/)